### ISSUE TITLE
Unable to deploy with  service variable 

### ISSUE THREAD

**Issue by ruthvik129** [anuradhawick/aws-lambda-serverless-boilerplate#1]
![image](https://user-images.githubusercontent.com/39596102/163370348-357bf008-349b-4b45-8b96-c3b87871e25f.png)

Followed the same boilerplate template , but facing this issue while deploying the same 

Just checking , if there are any workarounds for this

**Comment by anuradhawick** [comment]
Hi @ruthvik129,

You need to specify the service folder. For example,

```serverless deploy --stage dev--service services/reports```

Let me know if this helps. If not it is likely due to the versions I have used being out of date. Either way, let me know and I'll help.

You're welcome to PR changes if you find a way to fix this.

Thanks

Cheers

**Comment by ruthvik129** [comment]
Hey @anuradhawick 

Thanks for the reply , the custom CLI options have been deprecated from serverless v3 , the following workaround worked for me

https://www.serverless.com/framework/docs/deprecations/#UNSUPPORTED_CLI_OPTIONS

`functions: ${file(./${param:service}/service.yml):functions}`

and while deploying

`serverless deploy --stage dev --param="service=cities"`
